# Poverty Map (Google Earth Engine)

In [ ]:
### The VIIRS DNB dataset has 15 arcsec (about 463m at the equator) resolution nighttime luminosity. 
### We compute six aggregate summary statistics6 of the night light intensities within 1 square mile (1.6x1.6km2), 5x5km2, and 10x10km2 areas around each populated place.
### --> Max/mean/median luminosity, ratio of zero luminosity, average of upper/lower third luminosity.

## Setup

### Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!ln -s /content/drive/MyDrive/Colab\ Notebooks/SES-Inference /mydrive

Mounted at /content/drive

### Google Earth Engine

In [ ]:
import ee
ee.Authenticate()
ee.Initialize()

### Dependencies

In [ ]:
!pip install geopandas

In [6]:
### System
import sys
import itertools
from tqdm import tqdm

### Local
sys.path.append('/mydrive/libs/')
%set_env PYTHONPATH=/env/python:/mydrive/libs/

%load_ext autoreload
%autoreload 2

from maps import geo
from utils import ios
from maps.viirs import VIIRS

env: PYTHONPATH=/env/python:/mydrive/libs/
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Survey data (clusters)

In [7]:
### by DHS cluster
fn = '/mydrive/data/Uganda/results/DHS2016_MIS2018_iwi_cluster.csv'
df_dhs = ios.load_csv(fn, index_col=0)
df_dhs.head()

  DHSCC  DHSYEAR  DHSCLUST  URBAN_RURA  ...  ALT_DEM  DATUM   mean_iwi   SES
0    UG     2016         1           1  ...   1197.0  WGS84  43.300000  rich
1    UG     2016         2           1  ...   1179.0  WGS84  24.967857  rich
2    UG     2016         3           1  ...   1189.0  WGS84  34.732000  rich
3    UG     2016         4           1  ...   1181.0  WGS84  36.060714  rich
4    UG     2016         5           1  ...   1226.0  WGS84  44.857692  rich

[5 rows x 12 columns]

## Nightlight luminosity

### Examples

In [8]:
year = 2016
rad_gte_thres = 1.0

points = []
points.append([32.02786014765624,0.4653902099549784]) # Kampala (dark)
points.append([32.15326611328126,0.37593062258811094]) # Kampala (grey)
points.append([32.046836059570325,0.40373912169855747]) # Kampala (white)
points.append([8.66414963290783,50.118508372433]) # Frankfurt (white)
points.append([-73.97282574075544,40.779868876549926]) # Manhattan (white)

nl = VIIRS(source="viirs")
nl.filter(select='mean', date_start='{}-01-01'.format(year), date_end='{}-01-01'.format(year+1))
df = nl.fast_lights_at_points(points=points, buffer_meters=geo.KM_TO_M, rad_gte_thres=rad_gte_thres)
df.head(10)

   NTLL_1.0km_min  ...  NTLL_1.0km_rad_gte_1.0_sum_rad
0        0.014531  ...                             0.0
1        0.042873  ...                             0.0
2        1.471329  ...                             1.0
3       19.161980  ...                             1.0
4       30.965986  ...                             1.0

[5 rows x 9 columns]

### All-in-one (fast)

In [9]:
columns = ['DHSYEAR','LONGNUM','LATNUM']
df_dhs = df_dhs[columns].copy()
years = df_dhs.DHSYEAR.unique()
meters = geo.METERS
total = len(years)*len(meters)
rad_gte_thres = 10.0
newyear = -1

for year, meters in tqdm(itertools.product(years,meters), total=total):

  # constructor per year
  if newyear != year:
    nl = VIIRS(source="viirs")
    nl.filter(select='mean', date_start='{}-01-01'.format(year), date_end='{}-01-01'.format(year+1))
    newyear = year
    
  # points
  index = df_dhs.query("DHSYEAR==@year").index.values
  points = df_dhs.loc[index,['LONGNUM','LATNUM']].values
  df = nl.fast_lights_at_points(points=points, buffer_meters=meters, rad_gte_thres=rad_gte_thres)
  df.set_index(index, inplace=True)
  df_dhs.loc[index,df.columns.values] = df

100%|██████████| 8/8 [06:53<00:00, 51.69s/it]

In [ ]:
df_dhs = df_dhs[columns].copy()
df_dhs.drop(columns=columns, inplace=True)
df_dhs.sample(10)

    DHSCC  ...  NTLL_10.0km_rad_gte_10.0_sum_rad
526    UG  ...                          0.000000
578    UG  ...                          0.000000
215    UG  ...                          0.000000
374    UG  ...                          0.000000
88     UG  ...                          0.000000
604    UG  ...                          0.000000
563    UG  ...                          0.102969
670    UG  ...                          0.000000
746    UG  ...                          0.066873
256    UG  ...                          0.000000

[10 rows x 48 columns]