# Poverty Map (Facebook Marketing)

Estimate audience (# people)

## Setup

### Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!ln -s /content/drive/MyDrive/Colab\ Notebooks/SES-Inference /mydrive

Mounted at /content/drive

### Facebook Marketing

In [ ]:
!pip install facebook_business
!pip install geopandas

### Dependencies

In [3]:
### System
import sys
from tqdm import tqdm
import pandas as pd

### Local
sys.path.append('/mydrive/libs/')
%set_env PYTHONPATH=/env/python:/mydrive/libs/

%load_ext autoreload
%autoreload 2

from facebook.marketing import FacebookMarketing
from utils import ios
from maps import geo

env: PYTHONPATH=/env/python:/mydrive/libs/

## Examples

In [5]:
### TOKENS
fn_tokens = '/mydrive/data/Facebook/MarketingAPI/tokens/tokens1.json'
tokens = ios.load_json(fn_tokens)
access_token = tokens['access_token']
app_secret = tokens['app_secret']
ad_account_id = tokens['ad_account_id']
app_id = tokens['app_id']

### CONNECT
fbm = FacebookMarketing(app_id=app_id,
                        app_secret=app_secret,
                        access_token=access_token,
                        ad_account_id=ad_account_id)
fbm.init()

### LOCATIONS (lon,lat)
points = []
# points.append([32.02786014765624,0.4653902099549784]) # Kampala (dark)
# points.append([32.15326611328126,0.37593062258811094]) # Kampala (grey)
# points.append([32.046836059570325,0.40373912169855747]) # Kampala (white)
# points.append([8.66414963290783,50.118508372433]) # Frankfurt (white)
# points.append([-73.97282574075544,40.779868876549926]) # Manhattan (white)
# points.append([33.4583298577, 3.2037499184900002]) # Kampala (wrong location?)
# points.append([16.349574526841728, 48.166388205677045]) # Vienna
points.append([6.974701178001343, 50.936673977734294]) # Cologne

### USER PROFILES
# profiles = {'os_android':FacebookMarketing.OS_ANDROID, 
#             'behavior_frequent_traveler':FacebookMarketing.BEHAVIOR_FREQUENT_TRAVELER, 
#             'edu_highschool':FacebookMarketing.EDU_HIGHSCHOOL}

# profiles = {'le_away':{'life_events':[{'id':6003053860372, 'name':'Away from hometown'},{'id':6003053857372, 'name':'Away from family'}]},
#             'le_away_from_hometown':{'life_events':[{'id':6003053860372, 'name':'Away from hometown'}]},
#             'le_away_from_family':{'life_events':[{'id':6003053857372, 'name':'Away from family'}]}}

profiles = {'beh_browser':{'behaviors':[{'id':6015547847583, 'name':'Facebook access (browser): Firefox'},
                                          {'id':6015547900583, 'name':'Facebook access (browser): Chrome'},
                                          {'id':6015593608983, 'name':'Facebook access (browser): Safari'},
                                          {'id':6015593652183, 'name':'Facebook access (browser): Opera'},
                                          {'id':6015593776783, 'name':'Facebook access (browser): Internet Explorer'}]},
            'beh_firefox':{'behaviors':[{'id':6015547847583, 'name':'Facebook access (browser): Firefox'}]},
            'beh_chrome':{'behaviors':[{'id':6015547900583, 'name':'Facebook access (browser): Chrome'}]},
            'beh_safari':{'behaviors':[{'id':6015593608983, 'name':'Facebook access (browser): Safari'}]},
            'beh_opera':{'behaviors':[{'id':6015593652183, 'name':'Facebook access (browser): Opera'}]},
            'beh_explorer':{'behaviors':[{'id':6015593776783, 'name':'Facebook access (browser): Internet Explorer'}]},
            }
### QUERY
df = pd.DataFrame()
radius=geo.MILE_TO_M / geo.KM_TO_M
unit=FacebookMarketing.UNIT_KM
for id, point in enumerate(points):
  df = df.append(pd.DataFrame(index=[id]))

  for k,v in profiles.items():
    result,_ = fbm.get_reach_estimate(lon=point[0], lat=point[1], radius=radius, unit=unit, specific_params=v)
    df.loc[id,k] = None if result is None else result['users']
    
df.head(10)

   beh_browser  beh_firefox  beh_chrome  beh_safari  beh_opera  beh_explorer
0       9800.0       1400.0      4800.0      3500.0     1000.0        1000.0

In [15]:
!rm -rf /mydrive/cache/FBM*

## All-in-one (fast)

### Survey data (clusters)

In [ ]:
### by DHS cluster
fn = '/mydrive/data/Uganda/results/DHS2016_MIS2018_iwi_cluster.csv'
df_dhs = ios.load_csv(fn, index_col=0)
df_dhs.head()

  DHSCC  DHSYEAR  DHSCLUST  URBAN_RURA  ...  ALT_DEM  DATUM   mean_iwi   SES
0    UG     2016         1           1  ...   1197.0  WGS84  43.300000  rich
1    UG     2016         2           1  ...   1179.0  WGS84  24.967857  rich
2    UG     2016         3           1  ...   1189.0  WGS84  34.732000  rich
3    UG     2016         4           1  ...   1181.0  WGS84  36.060714  rich
4    UG     2016         5           1  ...   1226.0  WGS84  44.857692  rich

[5 rows x 12 columns]

### FB Reach

In [ ]:
### SET-UP
profiles = {'FBM_frequent_traveler':FacebookMarketing.BEHAVIOR_FREQUENT_TRAVELER,
            'FBM_small_business_owner':FacebookMarketing.BEHAVIOR_SMALL_BUSINESS_OWNER,
            'FBM_commuter':FacebookMarketing.BEHAVIOR_COMMUTER,
            'FBM_lives_abroad':FacebookMarketing.BEHAVIOR_LIVES_ABROAD,
            'FBM_frequent_int_traveler':FacebookMarketing.BEHAVIOR_FREQUENT_INTERNATIONAL_TRAVELER,
            'FBM_network_2G':FacebookMarketing.BEHAVIOR_NETWORK_2G,
            'FBM_network_3G':FacebookMarketing.BEHAVIOR_NETWORK_3G,
            'FBM_network_4G':FacebookMarketing.BEHAVIOR_NETWORK_4G,
            'FBM_feature_phone':FacebookMarketing.BEHAVIOR_FEATURE_PHONE,
            'FBM_old_device_os':FacebookMarketing.BEHAVIOR_OLD_DEVICE_OS,
            'FBM_mobile_access':FacebookMarketing.BEHAVIOR_MOBILE_ACCESS,
            'FBM_browser_access':FacebookMarketing.BEHAVIOR_BROWSER_ACCESS,
            'FBM_smartphone_tablet':FacebookMarketing.BEHAVIOR_SMARTPHONE_TABLET,
            'FBM_wifi':FacebookMarketing.BEHAVIOR_WIFI,
            'FBM_tech_early_adopter':FacebookMarketing.BEHAVIOR_TECHNOLOGY_EARLY_ADOPTERS,
            'FBM_returned_travel_1week':FacebookMarketing.BEHAVIOR_RETURNED_TRAVEL_1WEEK,
            'FBM_away_from_home':FacebookMarketing.LIFEEVENT_AWAY_FROM_HOME,
            'FBM_engaged':FacebookMarketing.LIFEEVENT_ENGAGED,
            'FBM_ind_gov':FacebookMarketing.INDUSTRY_GOV,
            'FBM_ind_business':FacebookMarketing.INDUSTRY_BUSINESS,
            'FBM_ind_legal':FacebookMarketing.INDUSTRY_LEGAL,
            'FBM_ind_it':FacebookMarketing.INDUSTRY_IT,
            'FBM_device_motorola':FacebookMarketing.DEVICE_MOTOROLA,
            'FBM_device_amazon':FacebookMarketing.DEVICE_AMAZON,
            'FBM_device_nokia':FacebookMarketing.DEVICE_NOKIA,
            'FBM_device_microsoft':FacebookMarketing.DEVICE_MICROSOFT,
            'FBM_os_ios':FacebookMarketing.OS_IOS,
            'FBM_os_android':FacebookMarketing.OS_ANDROID,
            'FBM_os_windows':FacebookMarketing.OS_WINDOWS,
            'FBM_os_windows_desktop':FacebookMarketing.OS_WINDOWS_DESKTOP,
            'FBM_os_windows_phone':FacebookMarketing.OS_WINDOWS_PHONE,
            'FBM_highschool':FacebookMarketing.EDU_HIGHSCHOOL,
            'FBM_bachelor':FacebookMarketing.EDU_BACHELOR,
            'FBM_master':FacebookMarketing.EDU_MASTER,
            'FBM_professional':FacebookMarketing.EDU_PROFESSIONAL,
            'FBM_phd':FacebookMarketing.EDU_PHD,
            'FBM_casino':FacebookMarketing.INTEREST_CASINO}

radius = geo.MILE_TO_M / geo.KM_TO_M
unit = FacebookMarketing.UNIT_KM
CACHE_DIR_LOCAL = '/content/FBM' 
CACHE_DIR_DRIVE = '/mydrive/data/Uganda/cache/FBM'
SLEEP = 60 * 30
MAXTOKENS = 10
print(radius, unit)

1.60934 kilometer

In [ ]:
!mkdir -p  $CACHE_DIR_LOCAL
!rsync $CACHE_DIR_DRIVE/ $CACHE_DIR_LOCAL

In [ ]:
!ls $CACHE_DIR_LOCAL | wc -lc
!ls $CACHE_DIR_DRIVE | wc -lc

  34014 2399647
  34014 2399647

In [ ]:
def fbconnect(tokenid):
  ### TOKENS
  fn_tokens = '/mydrive/data/Facebook/MarketingAPI/tokens{}.json'.format(tokenid)
  tokens = ios.load_json(fn_tokens)
  access_token = tokens['access_token']
  app_secret = tokens['app_secret']
  ad_account_id = tokens['ad_account_id']
  app_id = tokens['app_id']

  ### CONNECT
  fbm = FacebookMarketing(app_id=app_id,
                          app_secret=app_secret,
                          access_token=access_token,
                          ad_account_id=ad_account_id)
  fbm.init()
  return fbm

In [ ]:
from collections import defaultdict
from itertools import cycle
import time
import numpy as np
from datetime import datetime
import os

df_dhs_new = df_dhs.copy()
df_dhs_new = df_dhs_new[['LONGNUM','LATNUM']]

tokenids = cycle(np.arange(1,MAXTOKENS+1,1))
status = defaultdict(int)

tokenid = next(tokenids)
fbm = fbconnect(tokenid)
counter = 0
for id, row in df_dhs_new.iterrows():
  counter += 1
  print("========== {} of {} ==========".format(counter, df_dhs_new.shape[0]))
  
  ### QUERY
  for k,v in profiles.items():
    code = None
    while code not in [-1,0,2]:
      result, code = fbm.get_reach_estimate(lon=row.LONGNUM, lat=row.LATNUM, radius=radius, unit=unit, specific_params=v, cache_dir=CACHE_DIR_LOCAL) 
      value = None if result is None else result['users']
      df_dhs_new.loc[id,k] = value
      status[tokenid] = code == 1

      if code not in [-1,0]:
        print('code:', code)
      
      if status[tokenid]:
        print("token:{}, id:{}, result:fail".format(tokenid, id))
        
        if sum(list(status.values())) == MAXTOKENS:
          status = {k:0 for k,v in status.items()}
          current_time = datetime.now().strftime("%H:%M:%S")
          print('{}: sleeping {}min...'.format(current_time, SLEEP/60))
          
          ### save
          fn = '/mydrive/data/Uganda/results/DHS2016_MIS2018_iwi_cluster_Marketing.csv'
          ios.save_csv(df_dhs_new.drop(columns=['LONGNUM','LATNUM'], inplace=False), fn , index=True)
          ### cache to drive
          os.system("rsync -r {}/ {}".format(CACHE_DIR_LOCAL, CACHE_DIR_DRIVE))
          ### sleep 
          time.sleep(SLEEP)

        tokenid = next(tokenids)
        fbm = fbconnect(tokenid)

    if code==2:
      # skip wrong location
      break

os.system("rsync -r {}/ {}".format(CACHE_DIR_LOCAL, CACHE_DIR_DRIVE))

========== 1 of 1001 ==========
========== 2 of 1001 ==========
========== 3 of 1001 ==========
========== 4 of 1001 ==========
========== 5 of 1001 ==========
========== 6 of 1001 ==========
========== 7 of 1001 ==========
========== 8 of 1001 ==========
========== 9 of 1001 ==========
========== 10 of 1001 ==========
========== 11 of 1001 ==========
========== 12 of 1001 ==========
========== 13 of 1001 ==========
========== 14 of 1001 ==========
========== 15 of 1001 ==========
========== 16 of 1001 ==========
========== 17 of 1001 ==========
========== 18 of 1001 ==========
========== 19 of 1001 ==========
========== 20 of 1001 ==========
========== 21 of 1001 ==========
========== 22 of 1001 ==========
========== 23 of 1001 ==========
========== 24 of 1001 ==========
========== 25 of 1001 ==========
========== 26 of 1001 ==========
========== 27 of 1001 ==========
========== 28 of 1001 ==========
========== 29 of 1001 ==========
========== 30 of 1001 ==========
========== 31 of 1001 ==========
========== 32 of 1001 ==========
========== 33 of 1001 ==========
========== 34 of 1001 ==========
========== 35 of 1001 ==========
========== 36 of 1001 ==========
========== 37 of 1001 ==========
========== 38 of 1001 ==========
========== 39 of 1001 ==========
========== 40 of 1001 ==========
========== 41 of 1001 ==========
========== 42 of 1001 ==========
========== 43 of 1001 ==========
========== 44 of 1001 ==========
========== 45 of 1001 ==========
========== 46 of 1001 ==========
========== 47 of 1001 ==========
========== 48 of 1001 ==========
========== 49 of 1001 ==========
========== 50 of 1001 ==========
========== 51 of 1001 ==========
========== 52 of 1001 ==========
========== 53 of 1001 ==========
========== 54 of 1001 ==========
========== 55 of 1001 ==========
========== 56 of 1001 ==========
========== 57 of 1001 ==========
========== 58 of 1001 ==========
========== 59 of 1001 ==========
========== 60 of 1001 ==========
========== 61 of 1001 ==========
========== 62 of 1001 ==========
========== 63 of 1001 ==========
========== 64 of 1001 ==========
========== 65 of 1001 ==========
========== 66 of 1001 ==========
========== 67 of 1001 ==========
========== 68 of 1001 ==========
========== 69 of 1001 ==========
========== 70 of 1001 ==========
========== 71 of 1001 ==========
========== 72 of 1001 ==========
========== 73 of 1001 ==========
========== 74 of 1001 ==========
========== 75 of 1001 ==========
========== 76 of 1001 ==========
========== 77 of 1001 ==========
========== 78 of 1001 ==========
========== 79 of 1001 ==========
========== 80 of 1001 ==========
========== 81 of 1001 ==========
========== 82 of 1001 ==========
========== 83 of 1001 ==========
========== 84 of 1001 ==========
========== 85 of 1001 ==========
========== 86 of 1001 ==========
========== 87 of 1001 ==========
========== 88 of 1001 ==========
========== 89 of 1001 ==========
========== 90 of 1001 ==========
========== 91 of 1001 ==========
========== 92 of 1001 ==========
========== 93 of 1001 ==========
========== 94 of 1001 ==========
========== 95 of 1001 ==========
========== 96 of 1001 ==========
========== 97 of 1001 ==========
========== 98 of 1001 ==========
========== 99 of 1001 ==========
========== 100 of 1001 ==========
========== 101 of 1001 ==========
========== 102 of 1001 ==========
========== 103 of 1001 ==========
========== 104 of 1001 ==========
========== 105 of 1001 ==========
========== 106 of 1001 ==========
========== 107 of 1001 ==========
========== 108 of 1001 ==========
========== 109 of 1001 ==========
========== 110 of 1001 ==========
========== 111 of 1001 ==========
========== 112 of 1001 ==========
========== 113 of 1001 ==========
========== 114 of 1001 ==========
========== 115 of 1001 ==========
========== 116 of 1001 ==========
========== 117 of 1001 ==========
========== 118 of 1001 ==========
========== 119 of 1001 ==========
========== 120 of 1001 ==========
========== 121 of 1001 ==========
========== 122 of 1001 ==========
========== 123 of 1001 ==========
========== 124 of 1001 ==========
========== 125 of 1001 ==========
========== 126 of 1001 ==========
========== 127 of 1001 ==========
========== 128 of 1001 ==========
========== 129 of 1001 ==========
========== 130 of 1001 ==========
========== 131 of 1001 ==========
========== 132 of 1001 ==========
========== 133 of 1001 ==========
========== 134 of 1001 ==========
========== 135 of 1001 ==========
========== 136 of 1001 ==========
========== 137 of 1001 ==========
========== 138 of 1001 ==========
========== 139 of 1001 ==========
========== 140 of 1001 ==========
========== 141 of 1001 ==========
========== 142 of 1001 ==========
========== 143 of 1001 ==========
========== 144 of 1001 ==========
========== 145 of 1001 ==========
========== 146 of 1001 ==========
========== 147 of 1001 ==========
========== 148 of 1001 ==========
========== 149 of 1001 ==========
========== 150 of 1001 ==========
========== 151 of 1001 ==========
========== 152 of 1001 ==========
========== 153 of 1001 ==========
========== 154 of 1001 ==========
========== 155 of 1001 ==========
========== 156 of 1001 ==========
========== 157 of 1001 ==========
========== 158 of 1001 ==========
========== 159 of 1001 ==========
========== 160 of 1001 ==========
========== 161 of 1001 ==========
========== 162 of 1001 ==========
========== 163 of 1001 ==========
========== 164 of 1001 ==========
========== 165 of 1001 ==========
========== 166 of 1001 ==========
========== 167 of 1001 ==========
========== 168 of 1001 ==========
========== 169 of 1001 ==========
========== 170 of 1001 ==========
========== 171 of 1001 ==========
========== 172 of 1001 ==========
========== 173 of 1001 ==========
========== 174 of 1001 ==========
========== 175 of 1001 ==========
========== 176 of 1001 ==========
========== 177 of 1001 ==========
========== 178 of 1001 ==========
========== 179 of 1001 ==========
========== 180 of 1001 ==========
========== 181 of 1001 ==========
========== 182 of 1001 ==========
========== 183 of 1001 ==========
========== 184 of 1001 ==========
========== 185 of 1001 ==========
========== 186 of 1001 ==========
========== 187 of 1001 ==========
========== 188 of 1001 ==========
========== 189 of 1001 ==========
========== 190 of 1001 ==========
========== 191 of 1001 ==========
========== 192 of 1001 ==========
========== 193 of 1001 ==========
========== 194 of 1001 ==========
========== 195 of 1001 ==========
========== 196 of 1001 ==========
========== 197 of 1001 ==========
========== 198 of 1001 ==========
========== 199 of 1001 ==========
========== 200 of 1001 ==========
========== 201 of 1001 ==========
========== 202 of 1001 ==========
========== 203 of 1001 ==========
========== 204 of 1001 ==========
========== 205 of 1001 ==========
========== 206 of 1001 ==========
========== 207 of 1001 ==========
========== 208 of 1001 ==========
========== 209 of 1001 ==========
========== 210 of 1001 ==========
========== 211 of 1001 ==========
========== 212 of 1001 ==========
========== 213 of 1001 ==========
========== 214 of 1001 ==========
========== 215 of 1001 ==========
========== 216 of 1001 ==========
========== 217 of 1001 ==========
========== 218 of 1001 ==========
========== 219 of 1001 ==========
========== 220 of 1001 ==========
========== 221 of 1001 ==========
========== 222 of 1001 ==========
========== 223 of 1001 ==========
========== 224 of 1001 ==========
========== 225 of 1001 ==========
========== 226 of 1001 ==========
========== 227 of 1001 ==========
========== 228 of 1001 ==========
========== 229 of 1001 ==========
========== 230 of 1001 ==========
========== 231 of 1001 ==========
========== 232 of 1001 ==========
========== 233 of 1001 ==========
========== 234 of 1001 ==========
========== 235 of 1001 ==========
========== 236 of 1001 ==========
========== 237 of 1001 ==========
========== 238 of 1001 ==========
========== 239 of 1001 ==========
========== 240 of 1001 ==========
========== 241 of 1001 ==========
========== 242 of 1001 ==========
========== 243 of 1001 ==========
========== 244 of 1001 ==========
========== 245 of 1001 ==========
========== 246 of 1001 ==========
========== 247 of 1001 ==========
========== 248 of 1001 ==========
========== 249 of 1001 ==========
========== 250 of 1001 ==========
========== 251 of 1001 ==========
========== 252 of 1001 ==========
========== 253 of 1001 ==========
========== 254 of 1001 ==========
========== 255 of 1001 ==========
========== 256 of 1001 ==========
========== 257 of 1001 ==========
========== 258 of 1001 ==========
========== 259 of 1001 ==========
========== 260 of 1001 ==========
========== 261 of 1001 ==========
========== 262 of 1001 ==========
========== 263 of 1001 ==========
========== 264 of 1001 ==========
========== 265 of 1001 ==========
========== 266 of 1001 ==========
========== 267 of 1001 ==========
========== 268 of 1001 ==========
========== 269 of 1001 ==========
========== 270 of 1001 ==========
========== 271 of 1001 ==========
========== 272 of 1001 ==========
========== 273 of 1001 ==========
========== 274 of 1001 ==========
========== 275 of 1001 ==========
========== 276 of 1001 ==========
========== 277 of 1001 ==========
========== 278 of 1001 ==========
========== 279 of 1001 ==========
========== 280 of 1001 ==========
========== 281 of 1001 ==========
========== 282 of 1001 ==========
========== 283 of 1001 ==========
========== 284 of 1001 ==========
========== 285 of 1001 ==========
========== 286 of 1001 ==========
========== 287 of 1001 ==========
========== 288 of 1001 ==========
========== 289 of 1001 ==========
========== 290 of 1001 ==========
========== 291 of 1001 ==========
========== 292 of 1001 ==========
========== 293 of 1001 ==========
========== 294 of 1001 ==========
========== 295 of 1001 ==========
========== 296 of 1001 ==========
========== 297 of 1001 ==========
========== 298 of 1001 ==========
========== 299 of 1001 ==========
========== 300 of 1001 ==========
========== 301 of 1001 ==========
========== 302 of 1001 ==========
========== 303 of 1001 ==========
========== 304 of 1001 ==========
========== 305 of 1001 ==========
========== 306 of 1001 ==========
========== 307 of 1001 ==========
========== 308 of 1001 ==========
========== 309 of 1001 ==========
========== 310 of 1001 ==========
========== 311 of 1001 ==========
========== 312 of 1001 ==========
========== 313 of 1001 ==========
========== 314 of 1001 ==========
========== 315 of 1001 ==========
========== 316 of 1001 ==========
========== 317 of 1001 ==========
========== 318 of 1001 ==========
========== 319 of 1001 ==========
========== 320 of 1001 ==========
========== 321 of 1001 ==========
========== 322 of 1001 ==========
========== 323 of 1001 ==========
========== 324 of 1001 ==========
========== 325 of 1001 ==========
========== 326 of 1001 ==========
========== 327 of 1001 ==========
========== 328 of 1001 ==========
========== 329 of 1001 ==========
========== 330 of 1001 ==========
========== 331 of 1001 ==========
========== 332 of 1001 ==========
========== 333 of 1001 ==========
========== 334 of 1001 ==========
========== 335 of 1001 ==========
========== 336 of 1001 ==========
========== 337 of 1001 ==========
========== 338 of 1001 ==========
========== 339 of 1001 ==========
========== 340 of 1001 ==========
========== 341 of 1001 ==========
========== 342 of 1001 ==========
========== 343 of 1001 ==========
========== 344 of 1001 ==========
========== 345 of 1001 ==========
========== 346 of 1001 ==========
========== 347 of 1001 ==========
========== 348 of 1001 ==========
========== 349 of 1001 ==========
========== 350 of 1001 ==========
========== 351 of 1001 ==========
========== 352 of 1001 ==========
========== 353 of 1001 ==========
========== 354 of 1001 ==========
========== 355 of 1001 ==========
========== 356 of 1001 ==========
========== 357 of 1001 ==========
========== 358 of 1001 ==========
========== 359 of 1001 ==========
========== 360 of 1001 ==========
========== 361 of 1001 ==========
========== 362 of 1001 ==========
========== 363 of 1001 ==========
========== 364 of 1001 ==========
========== 365 of 1001 ==========
========== 366 of 1001 ==========
========== 367 of 1001 ==========
========== 368 of 1001 ==========
========== 369 of 1001 ==========
========== 370 of 1001 ==========
========== 371 of 1001 ==========
========== 372 of 1001 ==========
========== 373 of 1001 ==========
========== 374 of 1001 ==========
========== 375 of 1001 ==========
========== 376 of 1001 ==========
========== 377 of 1001 ==========
========== 378 of 1001 ==========
========== 379 of 1001 ==========
========== 380 of 1001 ==========
========== 381 of 1001 ==========
========== 382 of 1001 ==========
100 1487851 Call was not successful
code: 2
========== 383 of 1001 ==========
========== 384 of 1001 ==========
========== 385 of 1001 ==========
========== 386 of 1001 ==========
========== 387 of 1001 ==========
100 1487851 Call was not successful
code: 2
========== 388 of 1001 ==========
========== 389 of 1001 ==========
========== 390 of 1001 ==========
========== 391 of 1001 ==========
========== 392 of 1001 ==========
========== 393 of 1001 ==========
========== 394 of 1001 ==========
========== 395 of 1001 ==========
========== 396 of 1001 ==========
========== 397 of 1001 ==========
========== 398 of 1001 ==========
========== 399 of 1001 ==========
========== 400 of 1001 ==========
========== 401 of 1001 ==========
========== 402 of 1001 ==========
========== 403 of 1001 ==========
========== 404 of 1001 ==========
========== 405 of 1001 ==========
========== 406 of 1001 ==========
100 1487851 Call was not successful
code: 2
========== 407 of 1001 ==========
========== 408 of 1001 ==========
========== 409 of 1001 ==========
========== 410 of 1001 ==========
========== 411 of 1001 ==========
========== 412 of 1001 ==========
========== 413 of 1001 ==========
========== 414 of 1001 ==========
========== 415 of 1001 ==========
========== 416 of 1001 ==========
========== 417 of 1001 ==========
========== 418 of 1001 ==========
========== 419 of 1001 ==========
========== 420 of 1001 ==========
========== 421 of 1001 ==========
========== 422 of 1001 ==========
========== 423 of 1001 ==========
========== 424 of 1001 ==========
========== 425 of 1001 ==========
========== 426 of 1001 ==========
========== 427 of 1001 ==========
========== 428 of 1001 ==========
========== 429 of 1001 ==========
========== 430 of 1001 ==========
========== 431 of 1001 ==========
========== 432 of 1001 ==========
========== 433 of 1001 ==========
========== 434 of 1001 ==========
========== 435 of 1001 ==========
========== 436 of 1001 ==========
========== 437 of 1001 ==========
========== 438 of 1001 ==========
========== 439 of 1001 ==========
========== 440 of 1001 ==========
========== 441 of 1001 ==========
========== 442 of 1001 ==========
========== 443 of 1001 ==========
========== 444 of 1001 ==========
========== 445 of 1001 ==========
========== 446 of 1001 ==========
========== 447 of 1001 ==========
========== 448 of 1001 ==========
========== 449 of 1001 ==========
========== 450 of 1001 ==========
========== 451 of 1001 ==========
========== 452 of 1001 ==========
========== 453 of 1001 ==========
========== 454 of 1001 ==========
========== 455 of 1001 ==========
========== 456 of 1001 ==========
========== 457 of 1001 ==========
========== 458 of 1001 ==========
========== 459 of 1001 ==========
========== 460 of 1001 ==========
========== 461 of 1001 ==========
========== 462 of 1001 ==========
========== 463 of 1001 ==========
========== 464 of 1001 ==========
========== 465 of 1001 ==========
========== 466 of 1001 ==========
========== 467 of 1001 ==========
========== 468 of 1001 ==========
========== 469 of 1001 ==========
========== 470 of 1001 ==========
========== 471 of 1001 ==========
========== 472 of 1001 ==========
========== 473 of 1001 ==========
========== 474 of 1001 ==========
========== 475 of 1001 ==========
========== 476 of 1001 ==========
========== 477 of 1001 ==========
========== 478 of 1001 ==========
========== 479 of 1001 ==========
========== 480 of 1001 ==========
========== 481 of 1001 ==========
100 1487851 Call was not successful
code: 2
========== 482 of 1001 ==========
========== 483 of 1001 ==========
========== 484 of 1001 ==========
========== 485 of 1001 ==========
========== 486 of 1001 ==========
========== 487 of 1001 ==========
========== 488 of 1001 ==========
========== 489 of 1001 ==========
========== 490 of 1001 ==========
========== 491 of 1001 ==========
========== 492 of 1001 ==========
========== 493 of 1001 ==========
========== 494 of 1001 ==========
========== 495 of 1001 ==========
========== 496 of 1001 ==========
========== 497 of 1001 ==========
========== 498 of 1001 ==========
========== 499 of 1001 ==========
========== 500 of 1001 ==========
========== 501 of 1001 ==========
========== 502 of 1001 ==========
========== 503 of 1001 ==========
========== 504 of 1001 ==========
========== 505 of 1001 ==========
========== 506 of 1001 ==========
========== 507 of 1001 ==========
========== 508 of 1001 ==========
========== 509 of 1001 ==========
========== 510 of 1001 ==========
========== 511 of 1001 ==========
========== 512 of 1001 ==========
========== 513 of 1001 ==========
========== 514 of 1001 ==========
========== 515 of 1001 ==========
========== 516 of 1001 ==========
========== 517 of 1001 ==========
========== 518 of 1001 ==========
========== 519 of 1001 ==========
========== 520 of 1001 ==========
========== 521 of 1001 ==========
========== 522 of 1001 ==========
========== 523 of 1001 ==========
========== 524 of 1001 ==========
========== 525 of 1001 ==========
========== 526 of 1001 ==========
========== 527 of 1001 ==========
========== 528 of 1001 ==========
========== 529 of 1001 ==========
========== 530 of 1001 ==========
========== 531 of 1001 ==========
========== 532 of 1001 ==========
========== 533 of 1001 ==========
========== 534 of 1001 ==========
========== 535 of 1001 ==========
========== 536 of 1001 ==========
========== 537 of 1001 ==========
========== 538 of 1001 ==========
========== 539 of 1001 ==========
========== 540 of 1001 ==========
========== 541 of 1001 ==========
========== 542 of 1001 ==========
========== 543 of 1001 ==========
========== 544 of 1001 ==========
========== 545 of 1001 ==========
========== 546 of 1001 ==========
========== 547 of 1001 ==========
========== 548 of 1001 ==========
========== 549 of 1001 ==========
========== 550 of 1001 ==========
========== 551 of 1001 ==========
========== 552 of 1001 ==========
========== 553 of 1001 ==========
========== 554 of 1001 ==========
========== 555 of 1001 ==========
========== 556 of 1001 ==========
========== 557 of 1001 ==========
========== 558 of 1001 ==========
========== 559 of 1001 ==========
========== 560 of 1001 ==========
========== 561 of 1001 ==========
========== 562 of 1001 ==========
========== 563 of 1001 ==========
========== 564 of 1001 ==========
========== 565 of 1001 ==========
========== 566 of 1001 ==========
========== 567 of 1001 ==========
========== 568 of 1001 ==========
========== 569 of 1001 ==========
========== 570 of 1001 ==========
========== 571 of 1001 ==========
========== 572 of 1001 ==========
========== 573 of 1001 ==========
========== 574 of 1001 ==========
========== 575 of 1001 ==========
========== 576 of 1001 ==========
========== 577 of 1001 ==========
========== 578 of 1001 ==========
========== 579 of 1001 ==========
========== 580 of 1001 ==========
========== 581 of 1001 ==========
========== 582 of 1001 ==========
========== 583 of 1001 ==========
========== 584 of 1001 ==========
========== 585 of 1001 ==========
========== 586 of 1001 ==========

0

In [ ]:
df_dhs_new.drop(columns=['LONGNUM','LATNUM'], inplace=True)
df_dhs_new.head()

   FBM_frequent_traveler  FBM_small_business_owner  ...  FBM_professional  FBM_phd
0                66000.0                    7400.0  ...            1000.0   1000.0
1                68000.0                    7400.0  ...            1000.0   1000.0
2                75000.0                    8200.0  ...            1000.0   1000.0
3                42000.0                    4500.0  ...            1000.0   1000.0
4               580000.0                   72000.0  ...            1000.0   1000.0

[5 rows x 34 columns]